### ISSUE TITLE
issue with medaka

### ISSUE THREAD

**Issue by RobertRmendoza** [Saskia-Oosterbroek/decona#47]
Hi:

I installed decona and I get de racon results, however if I add the option -M it shows an error:

Filtering data...
Data filtered with NanoFilt
total raw sequences = 754
total filtered sequences = 483
Demultiplexing...
Multi threading is not yet supported in epi2mme mode. Falling back to using a single thread.
Adapters detected in 462 of 483 reads
  NBD104/NBD114    462: |  ################### |  95.65 %
           none     21: |                      |   4.35 %
Barcodes detected in 462 of 483 adapters
      barcode16    461: |  ################### |  95.45 %
      barcode22      1: |                      |   0.21 %
           none     21: |                      |   4.35 %
Demultiplexing finished in 0.67s
Data demultiplexed, working directory changed to:
/home/robertrm/03TEST/barcode16/demultiplexed_data
Fastq reads are being transformed to fasta
Transforming fastq to fasta Complete
Clustering reads...
Clustering barcode16/...
Clustering barcode22/...
Clustering complete.
Aligning and making draft assembly of 315-1.fa...
[M::mm_idx_gen::0.002*0.00] collected minimizers
[M::mm_idx_gen::0.003*0.00] sorted minimizers
[M::main::0.003*0.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.004*0.00] mid_occ = 3
[M::mm_idx_stat] kmer size: 8; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*0.00] distinct minimizers: 90 (98.89% are singletons); average occurrences: 1.011; average spacing: 5.791
[M::worker_pipeline::0.015*4.30] mapped 315 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax map-ont -k8 -t 4 ref_315-1.fasta 315-1.fa
[M::main] Real time: 0.016 sec; CPU: 0.062 sec; Peak RSS: 0.003 GB
[racon::Polisher::initialize] loaded target sequences 0.001075 s
[racon::Polisher::initialize] loaded sequences 0.001241 s
[racon::Polisher::initialize] loaded overlaps 0.000870 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.004352 s
[racon::Polisher::initialize] transformed data into windows 0.000348 s
[racon::Polisher::polish] generated consensus 0.273021 s
[racon::Polisher::] total = 0.282144 s
Done
Done
polishing 315-1.fa Racon sequence with Medaka...
Checking program versions
This is medaka 1.1.2
Program    Version    Required   Pass
bcftools   1.10.2     1.9        True
bgzip      1.10.2     1.9        True
minimap2   2.17       2.11       True
samtools   1.10       1.9        True
tabix      1.10.2     1.9        True
Aligning basecalls to draft
Removing previous index file /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/polished_315-1.fasta.mmi
Removing previous index file /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/polished_315-1.fasta.fai
Constructing minimap index.
[M::mm_idx_gen::0.001*0.00] collected minimizers
[M::mm_idx_gen::0.002*0.00] sorted minimizers
[M::main::0.004*0.00] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.004*0.00] distinct minimizers: 88 (100.00% are singletons); average occurrences: 1.000; average spacing: 6.068
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/polished_315-1.fasta.mmi /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/polished_315-1.fasta
[M::main] Real time: 0.006 sec; CPU: 0.000 sec; Peak RSS: 0.002 GB
[M::main::0.032*0.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.033*0.00] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.034*0.00] distinct minimizers: 88 (100.00% are singletons); average occurrences: 1.000; average spacing: 6.068
[M::worker_pipeline::0.047*1.33] mapped 315 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 4 -a -A 2 -B 4 -O 4,24 -E 2,1 /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/polished_315-1.fasta.mmi /home/robertrm/03TEST/barcode16/demultiplexed_data/barcode16/multi-seq/315-1.fa
[M::main] Real time: 0.051 sec; CPU: 0.062 sec; Peak RSS: 0.004 GB
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
Running medaka consensus
[18:37:20 - Predict] Processing region(s): 6721da47-6550-46d9-8d8f-3cbf44a89d34:0-534
[18:37:20 - Predict] Using model: /home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[18:37:20 - Predict] Setting tensorflow threads to 4.
[18:37:20 - Predict] Processing 1 long region(s) with batching.
[18:37:20 - ModelStore] filepath /home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[18:37:20 - ModelStore] ModelStore exception <class 'NotImplementedError'>
Traceback (most recent call last):
  File "/home/robertrm/anaconda3/envs/decona/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/medaka.py", line 669, in main
    args.func(args)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/prediction.py", line 136, in predict
    model = model_store.load_model(time_steps=args.chunk_len)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/datastore.py", line 77, in load_model
    model = model_partial_function(time_steps=time_steps)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/medaka/models.py", line 146, in build_model
    model.add(Bidirectional(gru, input_shape=input_shape))
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 208, in add
    layer(x)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 539, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 652, in call
    y = self.forward_layer(forward_inputs,
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 660, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 439, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 859, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 642, in get_initial_state
    init_state = get_initial_state_fn(
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1948, in get_initial_state
    return _generate_zero_filled_state_for_cell(self, inputs, batch_size, dtype)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2987, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3005, in _generate_zero_filled_state
    return create_zeros(state_size)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3000, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 180, in prod
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3045, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/robertrm/anaconda3/envs/decona/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_gru1/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
Failed to run medaka consensus.

Any help wpuld be appreciated

**Comment by Robvh-git** [comment]
Hi @RobertRmendoza 

could you run following code inside the decona environment and post the result:

```
pip show tensorflow numpy pandas
```

it is likely an version issue of the packages.
